server:
  port: 80

spring:
  application:
    name: cloudCusumerOrderConsul
  cloud:
    consul:
      instance-id: consul8005
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
